### ISSUE TITLE
The Default Spacing and Background color changing is not possible

### ISSUE THREAD

**Issue by vikasacharya16** [madmas/nativescript-pdf-view#10]
I Just tried to load the pdf by giving little bit space between each page on a black background.

when i just get inside the plugin I saw `var defaultSpacingDP = 8;` 

So i got that their is a spacing but because of white background the page spacing cannot be seen, If i'm not wrong.

is it possible to give an option to change the spacing and its background color.

**Comment by madmas** [comment]
@vick16ach Do you work with Android or iOS ?

The reason that we have a hard coded spacing is that it would be configureable for Android, but not for iOS, thus we decided to hardcode it to have a similar layout for both platforms.

**Comment by madmas** [comment]
@vikasacharya16 please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists.
