### ISSUE TITLE
loadComplete crashes on Android

### ISSUE THREAD

**Issue by shiv19** [madmas/nativescript-pdf-view#11]
https://github.com/barteksc/AndroidPdfViewer/issues/822

With version 2.1.0 of this plugin, I've been seeing some crashes on Android related to PdfViewer, it relates to the issue that I've linked above.
Going back to 2.0.1 until this is resolved :)

**Comment by armourjami** [comment]
Yes I've seen this issue as well. Roll back doesn't appear to be much better.

**Comment by shiv19** [comment]
@armourjami with 2.0.1 I'm not seeing any crash reports related to loadComplete so far 🤔

**Comment by sicbe** [comment]
I'm getting the same. Can't get it to work no matter what.

`System.err: An uncaught Exception occurred on "main" thread.
System.err: Attempt to invoke virtual method 'boolean android.os.HandlerThread.isAlive()' on a null object reference
System.err: 
System.err: StackTrace:
System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.HandlerThread.isAlive()' on a null object reference
System.err:     at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:756)
System.err:     at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:80)
System.err:     at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:27)
System.err:     at android.os.AsyncTask.finish(AsyncTask.java:695)
System.err:     at android.os.AsyncTask.-wrap1(Unknown Source:0)
System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6626)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
`

**Comment by sicbe** [comment]
And I'm just using this from the demo app.

`<PdfView src="https://www.princexml.com/samples/flyer/flyer.pdf" />`

**Comment by madmas** [comment]
@sicbe  @shiv19 @armourjami the stack trace looks a lot like a problem in the underlying Android library, as @shiv19 has reported. So we need to wait for a fix there and an update released.

**Comment by shiv19** [comment]
@madmas 
Someone has suggested a workaround until this is fixed 
https://github.com/barteksc/AndroidPdfViewer/issues/834#issuecomment-582356935

**Comment by madmas** [comment]
@shiv19 sounds interesting, but I don't think we can implement that workaround within the plugin.  

actually, looking at the open issues and PR for barteksc/AndroidPdfViewer, I'm concerned if there will be a update any time soon at all :(

**Comment by shiv19** [comment]
@madmas  that's sad :/
I'll stick to 2.0.1 till then :(

**Comment by madmas** [comment]
@shiv19 please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists.
