### ISSUE TITLE
Make the WebView take the entire height of PDF so I can use it in a ScrollView

### ISSUE THREAD

**Issue by darylteo** [madmas/nativescript-pdf-view#12]
Might be a hard one, understandable. But if it is possible, I'd like to have the option for the PDF Viewer to simply take the height of the document, so I can put it inside a ScrollView instead of it being just a frame around web content.

I am using nativescript-vue, typescript, and testing on iOS.

Thank you!
Daryl

**Comment by arturikoX** [comment]
Need this one too....

**Comment by madmas** [comment]
please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists.
