### ISSUE TITLE
Support for data:

### ISSUE THREAD

**Issue by davidpodhola** [madmas/nativescript-pdf-view#13]
Hello, 

this looks like a great package, thank you very much! 
Since our requests to get the PDF are authorization-protected, would you please accept a PR that would allow the `[src]` to be set in a way like `data:application/pdf;base64,${data}`?
Thanks and best,

David

**Comment by PReimers** [comment]
Hello @davidpodhola 

If you want to contribute a new feature or a bugfix, you're welcome to create a pull request.
@madmas will check (and merge) it then 😉

**Comment by lucacerretani** [comment]
Hello @davidpodhola, @madmas, @PReimers  
i've just created a pull request for this.
Hope it helps.

**Comment by lucacerretani** [comment]
Hi @madmas, 
let us know when you'll plan to release a new version 😃 
ty

**Comment by madmas** [comment]
@lucacerretani I plan to look into it this afternoon 😃

**Comment by madmas** [comment]
Just released it as 2.3.0 :-) Added a sample to the demo.
