### ISSUE TITLE
iOS - WKWebView affected by bug when switching views

### ISSUE THREAD

**Issue by darylteo** [madmas/nativescript-pdf-view#14]
https://stackoverflow.com/questions/58005508/wkwebview-pdf-issue-while-switching-the-tab

When swapping views, the already rendered PDF in a WKWebView disappears.

It is recommended to use PDFKit instead.

In the meantime, can you recommend a way I can get access to the underlying WKWebView to get it's scroll position so I can scroll back appropriate after reloading the pdf (by setting and unsetting the src property).

Thank you @madmas 
Daryl

**Comment by madmas** [comment]
Hi @darylteo 
a PR to migrate to PDFKit would be very welcome ;-)

you can access the WKWebView by `PDFView.ios` .

best

**Comment by madmas** [comment]
@darylteo please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists or you want to suggest the feature.
