### ISSUE TITLE
Go to Page

### ISSUE THREAD

**Issue by andipahlevy** [madmas/nativescript-pdf-view#18]
Is there is way to jump to x page?

**Comment by madmas** [comment]
@andipahlevy not yet, but would be a nice feature.

**Comment by madmas** [comment]
@andipahlevy  please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists or you want to suggest a feature
