### ISSUE TITLE
How to use this in Vue.js 2 with cordova

### ISSUE THREAD

**Issue by maheshkajaleinfobeans** [madmas/nativescript-pdf-view#22]
How to use this in Vue 2 along with the Cordova wrapper, please let me know. In my app, I want to display PDF files on ios and android devices.

**Comment by madmas** [comment]
@maheshkajaleinfobeans sorry, I don't know about a Cordova wrapper. is it something related to nativescript?

**Comment by maheshkajaleinfobeans** [comment]
@madmas, Thank you for your reply, actually I am developing a mobile application for ios/android using Vue js and Cordova. So how to use this above nativescript-pdf-view plugin in Vue js.

**Comment by madmas** [comment]
Hi @maheshkajaleinfobeans , this plugin is only for NativeScript, not Cordova. 
I strongly suggest you implement your app with NativeScript instead of Cordova ;-) 
I'll close this issue now, but feel free to still add any questions or comment.
