### ISSUE TITLE
iOS - Links within PDF open with URL Encoding "%23"

### ISSUE THREAD

**Issue by keithoys** [madmas/nativescript-pdf-view#24]
Is there any way (e.g. event listeners) to control the links that are opened from within the PDF? 

I have PDF documents that contains external hyperlinks with "%23"in the URL - supposedly the character '#' - and results in Error 404.

**Comment by madmas** [comment]
Unfortunately not. We would need to look into the components used on iOS and Android and see if such callback are available through their API. If yes, we could probably offer and API in the plugin as well.

**Comment by madmas** [comment]
@keithoys please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists or you want to suggest a feature...
