### ISSUE TITLE
Error occurs in XCode when running on a device/simulator with iOS v14 installed

### ISSUE THREAD

**Issue by peterdw** [madmas/nativescript-pdf-view#26]
XCode 12.0.1
Nativescript 6.5

Xcode: "Product -> Run" results in a totally blank screen on app startup.
**Error: Class "WKWebView" referenced by type encoding not found at runtime.**

If I remove the <PDFView> tags from my views, there is no problem.

Strangly when I debug this application in Visual Studio Code by using "Launch on iOS" on the same simulator, everything works fine.

Not sure if this is related to the plugin.

**Comment by madmas** [comment]
@peterdw with the new version of the plugin and NS7 around, compatibility to XCode 12 has improved. Also see the compatibility chart: https://nativescript.org/blog/nativescript-6-7-xcode-compatibility/

**Comment by madmas** [comment]
@peterdw please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists.
