### ISSUE TITLE
Error render PDF

### ISSUE THREAD

**Issue by Andres0323** [madmas/nativescript-pdf-view#30]
I am using this plugin in nativescript with angular. but when the PDF is opened in dark mode theme, it shows in black patches.
What I can do?

![WhatsApp Image 2021-01-02 at 12 05 17 PM](https://user-images.githubusercontent.com/42001943/103462398-eacc8280-4cf2-11eb-8dc9-87b8958e8376.jpeg)

**Comment by madmas** [comment]
@Andres0323  this is probably due to the backgound set to black and the PDF being rendered as transparent. Have you verified this with various PDFs?

**Comment by madmas** [comment]
@Andres0323 please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists.
