### ISSUE TITLE
NS 6.3.0

### ISSUE THREAD

**Issue by itsmerockingagain** [madmas/nativescript-pdf-view#32]
I am getting error when running this plugin in ns angular project

Package json dependency

    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.2.1",
    "@ngrx/effects": "^10.1.2",
    "@ngrx/entity": "^10.1.2",
    "@ngrx/store": "^10.1.2",
    "@ngrx/store-devtools": "^10.1.2",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "core-js": "^2.6.9",
    "nativescript-angular": "~8.20.0",
    "nativescript-drop-down": "^5.0.6",
    "nativescript-pdf-view": "^3.0.0-1",
    "nativescript-plugin-firebase": "^10.6.3",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.4.0",
    "tns-core-modules": "~6.3.0",
    "tslib": "1.10.0",
    "zone.js": "~0.9.1"

Error:on tns run android System.err: 

An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules/nativescript-pdf-view/common.js:26:7)
System.err: 
System.err: StackTrace: 
System.err: ../node_modules/nativescript-pdf-view/common.js(file: node_modules/nativescript-pdf-view/common.js:26:7)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:753:0)
System.err:     at fn(file: src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-pdf-view/index.js(file: node_modules/nativescript-pdf-view/index.android.js:1:0)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:753:0)
System.err:     at fn(file: src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-pdf-view/angular/fesm2015/nativescript-nativescript-pdf-view-angular.js(file: node_modules/nativescript-pdf-view/angular/fesm2015/nativescript-nativescript-pdf-view-angular.js:1:0)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:753:0)
System.err:     at fn(file: src/webpack/bootstrap:120:0)

**Comment by boris01** [comment]
@itsmerockingagain I think that version 3 of the plugin is for NS 7 and newer.
If you are using older NS version then use the latest 2.x version of this plugin.

**Comment by itsmerockingagain** [comment]
Thanks @boris01  for quick response, i will try to use version 2.x and update you.

**Comment by madmas** [comment]
@itsmerockingagain I hope you found a solution?

**Comment by madmas** [comment]
@itsmerockingagain please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists.
