### ISSUE TITLE
close pdf

### ISSUE THREAD

**Issue by bradrice** [madmas/nativescript-pdf-view#35]
Is there a way to add a close button to the pdf view? I have it like this in my template

`<StackLayout>
<GridLayout *ngIf="pdfUrl">
        <PDFView row="0" col="0" [src]="pdfUrl" (load)="onLoad()"></PDFView>
    </GridLayout>
    <ListView [items]="lessonDetail.doc" [height]="listheight" id="doclistview" class="list-items">
        <ng-template let-item="item" let-i="index" let-odd="odd" let-even="even">
            <GridLayout columns="*" rows="auto,auto" [class.odd]="odd" [class.even]="even" class="doc-list">
                <FlexboxLayout col="0" row="0" class="doc-list-item-layout">
                    <Image [src]="item.iconsrc" stretch="aspectFit"></Image>
                    <Label text='Download Student Reference' textWrap="true" [dataurl]="item.fileUrl" [id]="item.assetId" class="h3 doc-list-item" (tap)="openDoc($event)"></Label>
                </FlexboxLayout>
            </GridLayout>
        </ng-template>
    </ListView>
<StackLayout>`

When the item is clicked in the listview, if it is a pdf it does open that pdf viewer at the top, but I have no way to close it to go back to the list view. I suppose I could open a modal with a close button as an alternative.

**Comment by madmas** [comment]
@bradrice  please note we moved to the nativescript community plugin repo (https://github.com/NativeScript/plugins/blob/main/packages/pdf/README.md). Please re-open the issue there if it still persists.
