### ISSUE TITLE
Angular:  PDF on iOS cannot be changed at runtime

### ISSUE THREAD

**Issue by andreaboriani** [madmas/nativescript-pdf-view#6]
I need to change the PDF shown at runtime.
The first PDF I load is shown but if I change the variable bound to PDFView the shown PDF won't update.
On Android it is working as expected.

**Comment by alexander-mai** [comment]
I have the same problem.
I got it working by using *ngIf="pdfSrc" and setting pdfSrc to null and after a timeout to the new src.

**Comment by madmas** [comment]
@andreaboriani @alexander-mai Have you seen the demo app included with this repository? It does change the PDF during runtime when you click the buttom by changing the variables value: https://github.com/madmas/nativescript-pdf-view/blob/master/demo/app/main-view-model.ts

**Comment by alexander-mai** [comment]
I use Nativescript with Angular. Maybe it's an Angular specific problem.

I use it like
```javascript
<PDFView *ngIf="pdfSrc" row="0" [src]="pdfSrc"></PDFView>
```
This may fail because the value changes but the variable remains unchanged.

**Comment by madmas** [comment]
Hi @alexander-mai, I've created an sample (on a seperate branch to use ngIf and do not load a Pdf initially) which works quite well for me: 
https://github.com/madmas/nativescript-pdf-view-angular-sample/tree/demo_issue6_changePdfPathOnRuntime

Maye this helps to understand why it's not working in your case?
