### ISSUE TITLE
Samsung Galaxy S8 don't show PDF correctly

### ISSUE THREAD

**Issue by eduardojr3** [madmas/nativescript-pdf-view#7]
Hi, I have tested this plugin in several devices and emulators, and the PDFs are showing good but when I test in a Samsung Galaxy S8 device (I have tested in two), there are some characters that are replaced by a rectangle and the PDF don't look good. How can I do in order to correctly view the PDF in all Android devices?

I have tested in the following devices having the expected view (working OK):

- Samsung Galaxy S6
- Xiaomi MI9T
- Ipad Air 2
- Pixel XL (Virtual Device)
- iPhone 11 Pro Max (Simulator)

**Comment by madmas** [comment]
@eduardojr3 have you tried different PDFs? Is the font embedded with the PDF or might it be related to a font that is not available or roken on the S8 ?

**Comment by eduardojr3** [comment]
Thanks @madmas for your answer!
 
Aswering your questions: 

- Have you tried different PDFs? 
Yes, I can see perfectly its content

- Is the font embedded with the PDF or might it be related to a font that is not available or broken on the S8 ? 
The font is embedded with the PDF

I solved this issue changing the font from Verdana to Times New Roman
