### ISSUE TITLE
Halo NS-Vue

### ISSUE THREAD

**Issue by andipahlevy** [madmas/nativescript-pdf-view#8]
Can anyone give me how to display pdf with NS Vue?

**Comment by madmas** [comment]
HI @andipahlevy, I create a sample for you: https://github.com/madmas/nativescript-pdf-view-vue-sample

Hope it helps :)

Have fun coding with {N}!

**Comment by andipahlevy** [comment]
ok. really thanks Mr @madmas , i will try it
