### ISSUE TITLE
PDF doesn't load at all on Android

### ISSUE THREAD

**Issue by davecoffin** [madmas/nativescript-pdf-view#9]
When loading a pdf, i get this error on android:
`TypeError: this.android.fromUri(...).onLoad(...).spacing is not a function`

Comes from this line in `loadPDF`:
```
this.android
            .fromUri(uri)
            .onLoad(this.onLoadHandler)
            .spacing(defaultSpacingDP)
            .fitEachPage(true)
            .load();
```

I've stepped through the code and the uri looks fine.

**Comment by davecoffin** [comment]
Looks like it has to do with this commit: 
https://github.com/madmas/nativescript-pdf-view/commit/bdfd7f08152440cd420da2a6da275dca9a38b9ff

**Comment by madmas** [comment]
Hi @davecoffin , can you provide some example code? the current version works fine for me with Android and iOS.

**Comment by madmas** [comment]
Hey @davecoffin closing this, please let me know if the problem still persists
